# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160126_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='authors',
            new_name='status',
        ),
    ]
